name = "dealrank"
main = "worker.js"
compatibility_date = "2026-09-06"
keep_vars = true

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "dealrank-db"
database_id = "9ac167a1-548c-4746-b46d-d1b0c496ab80"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = false
head_sampling_rate = 1
persist = true
