name = "dealrank"
main = "worker.js"
compatibility_date = "2026-09-06"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "dealrank-db"
database_id = "9ac167a1-548c-4746-b46d-d1b0c496ab80"
